// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EWYa2_HzPx3aM7GbSrQOqCrnf3IA4Vk',
    appId: '1:72429524357:web:0316f62d857a074965a0ec',
    messagingSenderId: '72429524357',
    projectId: 'bayan-e-learning',
    authDomain: 'bayan-e-learning.firebaseapp.com',
    storageBucket: 'bayan-e-learning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pX16S-jaD0TRJFpHXAjfyO7w0ObLnl8',
    appId: '1:72429524357:android:e6c9d919abdeafe965a0ec',
    messagingSenderId: '72429524357',
    projectId: 'bayan-e-learning',
    storageBucket: 'bayan-e-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCqgm2Clq2cMNIeAeFvtu7GKupU06y3MU',
    appId: '1:72429524357:ios:181dec0990b9fd5c65a0ec',
    messagingSenderId: '72429524357',
    projectId: 'bayan-e-learning',
    storageBucket: 'bayan-e-learning.firebasestorage.app',
    iosBundleId: 'com.bayan.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCqgm2Clq2cMNIeAeFvtu7GKupU06y3MU',
    appId: '1:72429524357:ios:181dec0990b9fd5c65a0ec',
    messagingSenderId: '72429524357',
    projectId: 'bayan-e-learning',
    storageBucket: 'bayan-e-learning.firebasestorage.app',
    iosBundleId: 'com.bayan.elearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EWYa2_HzPx3aM7GbSrQOqCrnf3IA4Vk',
    appId: '1:72429524357:web:5e32e7e75ebc920e65a0ec',
    messagingSenderId: '72429524357',
    projectId: 'bayan-e-learning',
    authDomain: 'bayan-e-learning.firebaseapp.com',
    storageBucket: 'bayan-e-learning.firebasestorage.app',
  );

}